void f()
{
    throw std::runtime_error();
}

void g()
{
    throw;
}
